{
 "title": "Kexa Main Dashboard",
 "description": "Kexa dashboard for global management, history, last scan & more",
 "tags": [
  "Kexa",
  "Monitoring",
  "Security",
  "Compliance",
  "Costs",
  " Alerting"
 ],
 "time": { "from": "2024-08-19T04:44:06.262Z", "to": "2024-08-19T16:44:06.262Z" },
 "templating": {
  "list": [
   { "name": "KexaAddons", "label": "Kexa Addons", "query": "SELECT name FROM providers;" },
   { "name": "SourceDatabase", "label": "Source Database", "query": "grafana-postgresql-datasource" }
  ]
 },
 "panels": [
  { "title": "Last Scan", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Last Scan Total Resources Scanned",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    COUNT(*) AS total \r\nFROM \r\n    scans \r\nWHERE \r\n    batchId = (\r\n        SELECT batchId \r\n        FROM scans \r\n        WHERE created_at = (SELECT MAX(created_at) FROM scans)\r\n        LIMIT 1\r\n    );\r\n"
    }
   ]
  },
  {
   "title": "Error types",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    CASE \r\n        WHEN level = 0 THEN 'Info'\r\n        WHEN level = 1 THEN 'Warning'\r\n        WHEN level = 2 THEN 'Error'\r\n        WHEN level = 3 THEN 'Fatal'\r\n    END AS level_label,\r\n    COUNT(*) * 100.0 / SUM(COUNT(*)) OVER () AS percentage\r\nFROM \r\n    Scans\r\nJOIN \r\n    Rules ON Scans.ruleId = Rules.ID\r\nWHERE \r\n    Scans.error = true\r\n    AND Scans.batchId = (\r\n        SELECT batchId \r\n        FROM Scans \r\n        WHERE created_at = (SELECT MAX(created_at) FROM Scans)\r\n        LIMIT 1\r\n    )\r\nGROUP BY \r\n    level_label;"
    }
   ]
  },
  {
   "title": "Passed VS Errors",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  (SUM(CASE WHEN error = false THEN 1 ELSE 0 END) * 100.0 / COUNT(*)) AS \"Passed\",\r\n  (SUM(CASE WHEN error = true THEN 1 ELSE 0 END) * 100.0 / COUNT(*)) AS \"Error\"\r\nFROM\r\n  scans\r\nWHERE\r\n  batchId = (\r\n    SELECT batchId \r\n    FROM scans \r\n    WHERE created_at = (SELECT MAX(created_at) FROM scans)\r\n    LIMIT 1\r\n  );"
    }
   ]
  },
  {
   "title": "Resources To Remediate",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT\r\n    Resources.ID AS resource_id,\r\n    Resources.content AS resource_content,\r\n    Rules.name AS rule_name\r\nFROM\r\n    Resources\r\nJOIN\r\n    Scans ON Resources.ID = Scans.resourceId\r\nJOIN\r\n    Rules ON Scans.ruleId = Rules.ID\r\nWHERE\r\n    Scans.error = true\r\n    AND Scans.batchId = (\r\n        SELECT batchId\r\n        FROM Scans\r\n        WHERE created_at = (SELECT MAX(created_at) FROM Scans)\r\n        LIMIT 1\r\n    );"
    }
   ]
  },
  {
   "title": "Errors by Rule",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    Rules.name AS rule_name,\r\n    CASE\r\n        WHEN Rules.level = 0 THEN 'Info'\r\n        WHEN Rules.level = 1 THEN 'Warning'\r\n        WHEN Rules.level = 2 THEN 'Error'\r\n        WHEN Rules.level = 3 THEN 'Fatal'\r\n    END AS error_level,\r\n    COUNT(Scans.ID) AS error_count\r\nFROM\r\n    Scans\r\nJOIN\r\n    Rules ON Scans.ruleId = Rules.ID\r\nWHERE\r\n    Scans.error = true\r\n    AND Scans.batchId = (\r\n        SELECT batchId \r\n        FROM Scans \r\n        WHERE created_at = (SELECT MAX(created_at) FROM Scans)\r\n        LIMIT 1\r\n    )\r\nGROUP BY\r\n    Rules.name,\r\n    Rules.level\r\nORDER BY\r\n    error_count DESC;"
    }
   ]
  },
  { "title": "History", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Passed Tests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    MIN(created_at) AS scan_time,\r\n    batchId,\r\n    (COUNT(*) FILTER (WHERE error = false) * 100.0) / COUNT(*) AS error_percentage\r\nFROM \r\n    scans\r\nWHERE\r\n    created_at >= NOW() - INTERVAL '3 months'\r\nGROUP BY \r\n    batchId\r\nORDER BY \r\n    scan_time ASC;"
    }
   ]
  },
  {
   "title": "Errors by Rule",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    Rules.name AS rule_name,\r\n    CASE\r\n        WHEN Rules.level = 0 THEN 'Info'\r\n        WHEN Rules.level = 1 THEN 'Warning'\r\n        WHEN Rules.level = 2 THEN 'Error'\r\n        WHEN Rules.level = 3 THEN 'Fatal'\r\n    END AS error_level,\r\n    COUNT(Scans.ID) AS error_count\r\nFROM\r\n    Scans\r\nJOIN\r\n    Rules ON Scans.ruleId = Rules.ID\r\nWHERE\r\n    Scans.error = true\r\nGROUP BY\r\n    Rules.name,\r\n    Rules.level\r\nORDER BY\r\n    error_count DESC;\r\n"
    }
   ]
  },
  { "title": "Backup graph", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } }
 ]
}