{
 "title": "Kexa Kubernetes Limits & Request",
 "description": "Using Kexa to help identifying ",
 "tags": [
  "Monitoring",
  "Kubernetes",
  "Limits",
  "Requests",
  "CPU",
  "Memory",
  "Kexa"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "CpuRule",
    "label": "CPU Usage Rule Name",
    "query": "SELECT DISTINCT\n    Rules.name AS rule_name\nFROM\n    Rules\nJOIN\n    Providers ON Rules.providerId = Providers.ID\nWHERE\n    Providers.name = 'kubernetes';"
   },
   {
    "name": "MemoryRule",
    "label": "Memory Usage Rule Name",
    "query": "SELECT DISTINCT\n    Rules.name AS rule_name\nFROM\n    Rules\nJOIN\n    Providers ON Rules.providerId = Providers.ID\nWHERE\n    Providers.name = 'kubernetes';"
   },
   {
    "name": "Pod",
    "label": "Pod",
    "query": "SELECT DISTINCT\n    Resources.content::jsonb->>'podName' AS \"Pod Name\"\nFROM\n    Resources\nJOIN\n    Scans ON Resources.ID = Scans.resourceId\nJOIN\n    Rules ON Scans.ruleId = Rules.ID\nWHERE\n        Resources.content::jsonb->'metadata'->>'namespace'='$Namespace'\nORDER BY\n   Resources.content::jsonb->>'podName'\nASC;"
   },
   {
    "name": "Namespace",
    "label": "Namespace",
    "query": "SELECT DISTINCT\n    Resources.content::jsonb->'metadata'->>'namespace' AS \"Namespace\"\nFROM\n    Resources\nJOIN\n    Scans ON Resources.ID = Scans.resourceId\nJOIN\n    Rules ON Scans.ruleId = Rules.ID\nORDER BY\n    Resources.content::jsonb->'metadata'->>'namespace'\nASC;"
   },
   {
    "name": "CPULimit",
    "label": "CPU Limit Total",
    "query": "SELECT\n    Resources.content::jsonb->>'CPULimitTotal' AS \"CPU Limit Total\"\nFROM\n    Resources\nJOIN\n    Scans ON Resources.ID = Scans.resourceId\nJOIN\n    Rules ON Scans.ruleId = Rules.ID\nWHERE\n    Rules.name = '${CpuRule}'\n    AND Resources.content::jsonb->>'podName' = '${Pod}'\n    AND Scans.created_at = (\n        SELECT MAX(Scans.created_at)\n        FROM Scans\n        JOIN Resources ON Scans.resourceId = Resources.ID\n        JOIN Rules ON Scans.ruleId = Rules.ID\n        WHERE\n            Rules.name = '${CpuRule}'\n            AND Resources.content::jsonb->>'podName' = '${Pod}'\n    );"
   },
   {
    "name": "CPURequest",
    "label": "CPU Request Total",
    "query": "SELECT\n    Resources.content::jsonb->>'CPURequestTotal' AS \"CPU Request Total\"\nFROM\n    Resources\nJOIN\n    Scans ON Resources.ID = Scans.resourceId\nJOIN\n    Rules ON Scans.ruleId = Rules.ID\nWHERE\n    Rules.name = '${CpuRule}'\n    AND Resources.content::jsonb->>'podName' = '${Pod}'\n    AND Scans.created_at = (\n        SELECT MAX(Scans.created_at)\n        FROM Scans\n        JOIN Resources ON Scans.resourceId = Resources.ID\n        JOIN Rules ON Scans.ruleId = Rules.ID\n        WHERE\n            Rules.name = '${CpuRule}'\n            AND Resources.content::jsonb->>'podName' = '${Pod}'\n    );"
   },
   {
    "name": "MemoryLimit",
    "label": "Memory Limit Total",
    "query": "SELECT\n    Resources.content::jsonb->>'MemoryLimitTotal' AS \"Memory Limit Total\"\nFROM\n    Resources\nJOIN\n    Scans ON Resources.ID = Scans.resourceId\nJOIN\n    Rules ON Scans.ruleId = Rules.ID\nWHERE\n    Rules.name = '${MemoryRule}'\n    AND Resources.content::jsonb->>'podName' = '${Pod}'\n    AND Scans.created_at = (\n        SELECT MAX(Scans.created_at)\n        FROM Scans\n        WHERE\n            Scans.ruleId = Rules.ID\n            AND Scans.resourceId = Resources.ID\n    );"
   },
   { "name": "MemoryRequest", "label": "Memory Request Total" },
   { "name": "SourceDatabase", "label": "Source Database", "query": "grafana-postgresql-datasource" }
  ]
 },
 "panels": [
  { "title": "🌟 HELPERS 🌟", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Retrieved Kubernetes Rules From Last Scan",
   "type": "table",
   "description": "To help you find rule name of your peak alert rules and validate the connection",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT\r\n    Rules.name AS rule_name\r\nFROM\r\n    Rules\r\nJOIN\r\n    Providers ON Rules.providerId = Providers.ID\r\nWHERE\r\n    Providers.name = 'kubernetes';"
    }
   ]
  },
  {
   "title": "==========================================================================================================",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true
  },
  { "title": "☑️ SELECTED POD ☑️", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "CPU Limits & Request Configuration",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "cpu" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    '${CPULimit}' AS \"CPU Limit Total\",\r\n    '${CPURequest}' AS \"CPU Request Total\""
    }
   ]
  },
  {
   "title": "Memory Limits & Request Configuration",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    Resources.content::jsonb->>'MemoryLimitTotal' AS \"Memory Limit Total\",\r\n    Resources.content::jsonb->>'MemoryRequestTotal' AS \"Memory Request Total\",\r\n    Scans.created_at AS \"Latest Update\"\r\nFROM\r\n    Resources\r\nJOIN\r\n    Scans ON Resources.ID = Scans.resourceId\r\nJOIN\r\n    Rules ON Scans.ruleId = Rules.ID\r\nWHERE\r\n    Rules.name = '${MemoryRule}'\r\n    AND Resources.content::jsonb->>'podName' = '${Pod}'\r\n    AND Scans.created_at = (\r\n        SELECT MAX(Scans.created_at)\r\n        FROM Scans\r\n        JOIN Resources ON Scans.resourceId = Resources.ID\r\n        JOIN Rules ON Scans.ruleId = Rules.ID\r\n        WHERE\r\n            Rules.name = '${MemoryRule}'\r\n            AND Resources.content::jsonb->>'podName' = '${Pod}'\r\n    );\r\n"
    }
   ]
  },
  {
   "title": "CPU for ${Pod}",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    Resources.content::jsonb->>'podName' AS \"Pod Name\",\r\n    Resources.content::jsonb->>'name' AS \"Name\",\r\n    Resources.content::jsonb->>'CPUUsage' AS \"CPU Usage\",\r\n    Scans.created_at AS \"Time\",\r\n    Rules.name AS rule_name\r\nFROM\r\n    Resources\r\nJOIN\r\n    Scans ON Resources.ID = Scans.resourceId\r\nJOIN\r\n    Rules ON Scans.ruleId = Rules.ID\r\nWHERE\r\n    Rules.name = '${CpuRule}'\r\n    AND Resources.content::jsonb->>'podName' = '${Pod}'\r\nORDER BY\r\n    Scans.created_at;"
    }
   ]
  },
  {
   "title": "Memory for ${Pod}",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    Resources.content::jsonb->>'podName' AS \"Pod Name\",\r\n    Resources.content::jsonb->>'name' AS \"Name\",\r\n    Resources.content::jsonb->>'MemoryUsage' AS \"Memory Usage\",\r\n    Scans.created_at AS \"Time\",\r\n    Rules.name AS rule_name\r\nFROM\r\n    Resources\r\nJOIN\r\n    Scans ON Resources.ID = Scans.resourceId\r\nJOIN\r\n    Rules ON Scans.ruleId = Rules.ID\r\nWHERE\r\n    Rules.name = '${MemoryRule}'\r\n    AND Resources.content::jsonb->>'podName' = '${Pod}'\r\nORDER BY\r\n    Scans.created_at;"
    }
   ]
  },
  {
   "title": "Memory for ${Pod}",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    Resources.content::jsonb->>'podName' AS \"Pod Name\",\r\n    Resources.content::jsonb->>'name' AS \"Name\",\r\n    Resources.content::jsonb->>'CPUUsage' AS \"CPU Usage\",\r\n    Resources.content::jsonb->>'CPULimitTotal' AS \"CPU Limit\",\r\n    Resources.content::jsonb->>'CPURequestTotal' AS \"CPU Request\",\r\n    Scans.created_at AS \"Time\",\r\n    Rules.name AS rule_name\r\nFROM\r\n    Resources\r\nJOIN\r\n    Scans ON Resources.ID = Scans.resourceId\r\nJOIN\r\n    Rules ON Scans.ruleId = Rules.ID\r\nWHERE\r\n    Rules.name = '${CpuRule}'\r\n    AND Resources.content::jsonb->>'podName' = '${Pod}'\r\nORDER BY\r\n    Scans.created_at;"
    }
   ]
  },
  {
   "title": "Memory for ${Pod}",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    Resources.content::jsonb->>'podName' AS \"Pod Name\",\r\n    Resources.content::jsonb->>'name' AS \"Name\",\r\n    Resources.content::jsonb->>'MemoryUsage' AS \"Memory Usage\",\r\n    Resources.content::jsonb->>'MemoryLimitTotal' AS \"Memory Limit\",\r\n    Resources.content::jsonb->>'MemoryRequestTotal' AS \"Memory Request\",\r\n    Scans.created_at AS \"Time\",\r\n    Rules.name AS rule_name\r\nFROM\r\n    Resources\r\nJOIN\r\n    Scans ON Resources.ID = Scans.resourceId\r\nJOIN\r\n    Rules ON Scans.ruleId = Rules.ID\r\nWHERE\r\n    Rules.name = '${MemoryRule}'\r\n    AND Resources.content::jsonb->>'podName' = '${Pod}'\r\nORDER BY\r\n    Scans.created_at;"
    }
   ]
  },
  {
   "title": "CPU for ${Pod}",
   "type": "gauge",
   "gridPos": { "h": 13, "w": 4, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "CPU" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    MIN(CAST(Resources.content::jsonb->>'CPUUsage' AS NUMERIC)) AS \"Min Usage\",\r\n    AVG(CAST(Resources.content::jsonb->>'CPUUsage' AS NUMERIC)) AS \"Avg Usage\",\r\n    MAX(CAST(Resources.content::jsonb->>'CPUUsage' AS NUMERIC)) AS \"Max Usage\"\r\nFROM\r\n    Resources\r\nJOIN\r\n    Scans ON Resources.ID = Scans.resourceId\r\nJOIN\r\n    Rules ON Scans.ruleId = Rules.ID\r\nWHERE\r\n    Rules.name = '${CpuRule}'\r\n    AND Resources.content::jsonb->>'podName' = '${Pod}';\r\n"
    }
   ]
  },
  {
   "title": "Peak CPU Alerts with rule '${CpuRule}'",
   "type": "table",
   "gridPos": { "h": 13, "w": 8, "x": 4, "y": 23 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    Resources.content::jsonb->>'podName' AS \"Pod Name\",\r\n    Resources.content::jsonb->>'name' AS \"Name\",\r\n    Scans.created_at AS \"Scan time\"\r\nFROM\r\n    Resources\r\nJOIN\r\n    Scans ON Resources.ID = Scans.resourceId\r\nJOIN\r\n    Rules ON Scans.ruleId = Rules.ID\r\nWHERE\r\n    Scans.error = true\r\n    AND\r\n    (Rules.name = '${CpuRule}'\r\n    AND Resources.content::jsonb->>'podName' = '${Pod}')\r\nORDER BY\r\n    Scans.created_at\r\nDESC;"
    }
   ]
  },
  {
   "title": "Memory for ${Pod}",
   "type": "gauge",
   "gridPos": { "h": 13, "w": 4, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    MIN(CAST(Resources.content::jsonb->>'MemoryUsage' AS NUMERIC)) AS \"Min Usage\",\r\n    AVG(CAST(Resources.content::jsonb->>'MemoryUsage' AS NUMERIC)) AS \"Avg Usage\",\r\n    MAX(CAST(Resources.content::jsonb->>'MemoryUsage' AS NUMERIC)) AS \"Max Usage\"\r\nFROM\r\n    Resources\r\nJOIN\r\n    Scans ON Resources.ID = Scans.resourceId\r\nJOIN\r\n    Rules ON Scans.ruleId = Rules.ID\r\nWHERE\r\n    Rules.name = '${MemoryRule}'\r\n    AND Resources.content::jsonb->>'podName' = '${Pod}';\r\n"
    }
   ]
  },
  {
   "title": "Peak Memory Alerts with rule '${MemoryRule}'",
   "type": "table",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 23 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    Resources.content::jsonb->>'podName' AS \"Pod Name\",\r\n    Resources.content::jsonb->>'name' AS \"Name\",\r\n    Scans.created_at AS \"Scan time\"\r\nFROM\r\n    Resources\r\nJOIN\r\n    Scans ON Resources.ID = Scans.resourceId\r\nJOIN\r\n    Rules ON Scans.ruleId = Rules.ID\r\nWHERE\r\n    Scans.error = true\r\n    AND\r\n    Rules.name = '${MemoryRule}'\r\n    AND Resources.content::jsonb->>'podName' = '${Pod}'\r\nORDER BY\r\n    Scans.created_at\r\nDESC;"
    }
   ]
  },
  {
   "title": "TEST",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH OptimizationStats AS (\r\n    SELECT\r\n        CAST(Resources.content::jsonb->>'CPUUsage' AS NUMERIC) AS MemoryUsage,\r\n        CAST(Resources.content::jsonb->>'CPULimitTotal' AS NUMERIC) AS MemoryLimitTotal,\r\n        CAST(Resources.content::jsonb->>'CPURequestTotal' AS NUMERIC) AS MemoryRequestTotal\r\n    FROM\r\n        Resources\r\n    JOIN\r\n        Scans ON Resources.ID = Scans.resourceId\r\n    JOIN\r\n        Rules ON Scans.ruleId = Rules.ID\r\n    WHERE\r\n        Rules.name = '${CpuRule}'\r\n        AND Resources.content::jsonb->>'podName' = '${Pod}'\r\n)\r\nSELECT\r\n    AVG(\r\n        CASE\r\n            WHEN MemoryRequestTotal = 0 OR MemoryLimitTotal = 0 THEN 0\r\n            \r\n            ELSE 100 - 100 * ABS(MemoryUsage - COALESCE(NULLIF(MemoryRequestTotal, 0), MemoryLimitTotal)) / \r\n                COALESCE(NULLIF(MemoryLimitTotal - MemoryRequestTotal, 0), MemoryLimitTotal)\r\n        END\r\n    ) AS \"Optimization Percentage\"\r\nFROM\r\n    OptimizationStats;\r\n"
    }
   ]
  },
  {
   "title": "TEST",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH OptimizationStats AS (\r\n    SELECT\r\n        CAST(Resources.content::jsonb->>'MemoryUsage' AS NUMERIC) AS MemoryUsage,\r\n        CAST(Resources.content::jsonb->>'MemoryLimitTotal' AS NUMERIC) AS MemoryLimitTotal,\r\n        CAST(Resources.content::jsonb->>'MemoryRequestTotal' AS NUMERIC) AS MemoryRequestTotal\r\n    FROM\r\n        Resources\r\n    JOIN\r\n        Scans ON Resources.ID = Scans.resourceId\r\n    JOIN\r\n        Rules ON Scans.ruleId = Rules.ID\r\n    WHERE\r\n        Rules.name = '${MemoryRule}'\r\n        AND Resources.content::jsonb->>'podName' = '${Pod}'\r\n)\r\nSELECT\r\n    AVG(\r\n        CASE\r\n            WHEN MemoryRequestTotal = 0 OR MemoryLimitTotal = 0 THEN 0\r\n            \r\n            ELSE 100 - 100 * ABS(MemoryUsage - COALESCE(NULLIF(MemoryRequestTotal, 0), MemoryLimitTotal)) / \r\n                COALESCE(NULLIF(MemoryLimitTotal - MemoryRequestTotal, 0), MemoryLimitTotal)\r\n        END\r\n    ) AS \"Optimization Percentage\"\r\nFROM\r\n    OptimizationStats;\r\n"
    }
   ]
  },
  {
   "title": "TEST",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH UsageStats AS (\r\n    SELECT\r\n        MIN(CAST(Resources.content::jsonb->>'MemoryUsage' AS NUMERIC)) AS MinUsage,\r\n        MAX(CAST(Resources.content::jsonb->>'MemoryUsage' AS NUMERIC)) AS MaxUsage,\r\n        AVG(CAST(Resources.content::jsonb->>'MemoryUsage' AS NUMERIC)) AS AvgUsage\r\n    FROM\r\n        Resources\r\n    JOIN\r\n        Scans ON Resources.ID = Scans.resourceId\r\n    JOIN\r\n        Rules ON Scans.ruleId = Rules.ID\r\n    WHERE\r\n        Rules.name = '${MemoryRule}'\r\n        AND Resources.content::jsonb->>'podName' = '${Pod}'\r\n)\r\nSELECT\r\n    (ABS(AvgUsage - MinUsage) + ABS(MaxUsage - AvgUsage)) / 2 AS \"Avg Deviation\",\r\n    CASE\r\n        WHEN (MaxUsage - MinUsage) = 0 THEN 0\r\n        ELSE (ABS(AvgUsage - MinUsage) / (MaxUsage - MinUsage)) * 100\r\n    END AS \"Optimization Score (%)\",\r\n    MaxUsage - MinUsage AS \"Min Max Range\"\r\nFROM\r\n    UsageStats;\r\n"
    }
   ]
  },
  {
   "title": "TEST",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH UsageStats AS (\r\n    SELECT\r\n        MIN(CAST(Resources.content::jsonb->>'CPUUsage' AS NUMERIC)) AS MinUsage,\r\n        MAX(CAST(Resources.content::jsonb->>'CPUUsage' AS NUMERIC)) AS MaxUsage,\r\n        AVG(CAST(Resources.content::jsonb->>'CPUUsage' AS NUMERIC)) AS AvgUsage\r\n    FROM\r\n        Resources\r\n    JOIN\r\n        Scans ON Resources.ID = Scans.resourceId\r\n    JOIN\r\n        Rules ON Scans.ruleId = Rules.ID\r\n    WHERE\r\n        Rules.name = '${CpuRule}'\r\n        AND Resources.content::jsonb->>'podName' = '${Pod}'\r\n)\r\nSELECT\r\n    (ABS(AvgUsage - MinUsage) + ABS(MaxUsage - AvgUsage)) / 2 AS \"Avg Deviation\",\r\n    CASE\r\n        WHEN (MaxUsage - MinUsage) = 0 THEN 0\r\n        ELSE (ABS(AvgUsage - MinUsage) / (MaxUsage - MinUsage)) * 100\r\n    END AS \"Optimization Score (%)\",\r\n    MaxUsage - MinUsage AS \"Min Max Range\"\r\nFROM\r\n    UsageStats;\r\n"
    }
   ]
  },
  {
   "title": "==========================================================================================================",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true
  },
  { "title": "⚡⚡ CONSUMPTION PEAKS ⚡⚡", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Peak CPU & Memory Alerts (Global)",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT\r\n    Resources.content::jsonb->>'podName' AS \"Pod Name\",\r\n    Resources.content::jsonb->>'name' AS \"Name\",\r\n    Resources.content::jsonb->'metadata'->>'namespace' AS \"Namespace\",\r\n    Rules.name AS \"Rule Name\",\r\n    Scans.created_at AS \"Scan time\"\r\nFROM\r\n    Resources\r\nJOIN\r\n    Scans ON Resources.ID = Scans.resourceId\r\nJOIN\r\n    Rules ON Scans.ruleId = Rules.ID\r\nWHERE\r\n    Rules.name = '${CpuRule}' OR Rules.name = '${MemoryRule}'\r\nORDER BY\r\n    Scans.created_at\r\nDESC;"
    }
   ]
  },
  {
   "title": "Scan by scan bars with amount of peakk alert",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 20, "x": 0, "y": 51 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    COUNT(*) FILTER (WHERE s.error = true) AS \"Error Count\",\r\n    MAX(s.created_at) AS \"Latest Created At\"\r\nFROM\r\n    Scans s\r\nJOIN \r\n    Rules r ON s.ruleId = r.ID\r\nWHERE \r\n    s.error = true\r\n    AND (r.name = '${CpuRule}' OR r.name = '${MemoryRule}')\r\nGROUP BY \r\n    s.batchId\r\nORDER BY \r\n    \"Latest Created At\" ASC;\r\n"
    }
   ]
  },
  {
   "title": "Peak Hour",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "H~" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH HourlyUsage AS (\r\n    SELECT\r\n        EXTRACT(HOUR FROM Scans.created_at) AS \"Hour\",\r\n        SUM((Resources.content::jsonb->>'MemoryUsage')::numeric) AS \"Total Memory Usage\"\r\n    FROM\r\n        Resources\r\n    JOIN\r\n        Scans ON Resources.ID = Scans.resourceId\r\n    JOIN\r\n        Rules ON Scans.ruleId = Rules.ID\r\n    WHERE\r\n        Rules.name = '${CpuRule}'\r\n        AND Resources.content::jsonb->>'podName' = '${Pod}'\r\n    GROUP BY\r\n        EXTRACT(HOUR FROM Scans.created_at)\r\n)\r\nSELECT\r\n    \"Hour\"\r\nFROM\r\n    HourlyUsage\r\nORDER BY\r\n    \"Total Memory Usage\" DESC\r\nLIMIT 1;\r\n"
    }
   ]
  },
  {
   "title": "Peak Day",
   "type": "canvas",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "H~" } },
   "targets": [
    {
     "rawSql": "WITH WeeklyUsage AS (\r\n    SELECT\r\n        EXTRACT(DOW FROM Scans.created_at) AS \"DayOfWeek\",\r\n        SUM((Resources.content::jsonb->>'MemoryUsage')::numeric) AS \"Total Memory Usage\"\r\n    FROM\r\n        Resources\r\n    JOIN\r\n        Scans ON Resources.ID = Scans.resourceId\r\n    JOIN\r\n        Rules ON Scans.ruleId = Rules.ID\r\n    WHERE\r\n        Rules.name = '${CpuRule}'\r\n        AND Resources.content::jsonb->>'podName' = '${Pod}'\r\n    GROUP BY\r\n        EXTRACT(DOW FROM Scans.created_at)\r\n)\r\nSELECT\r\n    CASE \"DayOfWeek\"\r\n        WHEN 0 THEN 'Sunday'\r\n        WHEN 1 THEN 'Monday'\r\n        WHEN 2 THEN 'Tuesday'\r\n        WHEN 3 THEN 'Wednesday'\r\n        WHEN 4 THEN 'Thursday'\r\n        WHEN 5 THEN 'Friday'\r\n        WHEN 6 THEN 'Saturday'\r\n    END AS \"Peak Day of Week\"\r\nFROM\r\n    WeeklyUsage\r\nORDER BY\r\n    \"Total Memory Usage\" DESC\r\nLIMIT 1;\r\n"
    }
   ]
  },
  {
   "title": "Memory Usage Per hour (avg on all data)",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    DATE_TRUNC('hour', Scans.created_at) + INTERVAL '1 minute' * (FLOOR(EXTRACT(MINUTE FROM Scans.created_at) / 30) * 30) AS \"30 Minute Interval\",\r\n    SUM((Resources.content::jsonb->>'MemoryUsage')::numeric) AS \"Total Memory Usage\"\r\nFROM\r\n    Resources\r\nJOIN\r\n    Scans ON Resources.ID = Scans.resourceId\r\nJOIN\r\n    Rules ON Scans.ruleId = Rules.ID\r\nWHERE\r\n    Rules.name = '${CpuRule}'\r\n    AND Resources.content::jsonb->>'podName' = '${Pod}'\r\nGROUP BY\r\n    DATE_TRUNC('hour', Scans.created_at) + INTERVAL '1 minute' * (FLOOR(EXTRACT(MINUTE FROM Scans.created_at) / 30) * 30)\r\nORDER BY\r\n    \"30 Minute Interval\";\r\n"
    }
   ]
  },
  {
   "title": "==========================================================================================================",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 },
   "collapsed": true
  }
 ]
}